FROM alpine

RUN apk add --no-cache bash python3 py3-pip sqlite
RUN pip3 install b2 --upgrade --ignore-installed --break-system-packages
RUN mkdir /bbb
WORKDIR /bbb

COPY ../src/vaultwarden/backup.sh .
RUN mkdir common
COPY ../src/common ./common

ENV NTFY_SUCCESS_TITLE="vaultwarden backup succeeded"
ENV NTFY_SUCCESS_PRIORITY="1"
ENV NTFY_FAILURE_TITLE="vaultwarden backup failed"
ENV NTFY_FAILURE_PRIORITY="5"

ENTRYPOINT [ "./common/start.sh" ]
CMD [ "./backup.sh" ]