FROM alpine

RUN apk add --no-cache bash python3 py3-pip tar
RUN pip3 install b2 --upgrade --ignore-installed --break-system-packages
RUN mkdir /bbb
WORKDIR /bbb

COPY ../src/lubelogger/backup.py .
RUN mkdir common
COPY ../src/common ./common

ENV NTFY_SUCCESS_TITLE="lubelogger backup succeeded"
ENV NTFY_SUCCESS_PRIORITY="1"
ENV NTFY_FAILURE_TITLE="lubelogger backup failed"
ENV NTFY_FAILURE_PRIORITY="5"

ENTRYPOINT [ "./common/start.sh" ]
CMD [ "./backup.py" ]
